###########################################################################
# Dockerfile
###########################################################################

# FROM node:10-alpine
FROM node:16.13.2

COPY api-implementation /usr/local/platform-api-server

CMD /usr/local/platform-api-server/start.server.sh

# The end.
