###########################################################################
# Dockerfile
###########################################################################

# FROM node:10-alpine
FROM node:12.21

COPY api-implementation /usr/local/platform-api-server

CMD /usr/local/platform-api-server/start.server.sh

# The end.
